### ISSUE TITLE
Bug: Radar is showing targets from previous areas

### ISSUE THREAD

**Issue by boneyfinger** [Icehunter/ffxivapp-plugin-radar#39]
bug since patch 3.1
screenshot example attached

![radar_screenshot](https://cloud.githubusercontent.com/assets/16196394/11637511/c4d8c36a-9d19-11e5-8e2a-15557d08ec46.jpg)

**Comment by cybaersam** [comment]
in my latest commit/pull request i've made a temporary fix
so this shouldn't happen anymore...
also this remove dead mobs as soon as they are killed 

though... this fix is only for the monsters

**Comment by Icehunter** [comment]
I'm wondering if this is because I send the items as a dictionary and they are actually still in ram? Maybe this is something that can be a fix in the memory dll; or maybe it's a bug in there as well. ^^

**Comment by cybaersam** [comment]
could be...
i haven't actually to look in the ram for this...
i'm not good with that stuff... so i will need to look a few things up first... that is if you're already occupied with something else ^_^

**Comment by viion** [comment]
Yes they will be still in memory, the size is very big (up to hundreds) and will maintain a list of everything you've previously seen. Experienced this first hand when mapping out NPC's and Enemies and I would zone and it would still detect the previous zone stuff. Zoning does not remove them.

**Comment by Icehunter** [comment]
A good idea would be to see if my structure size is too large, or is it the area of ram in which those things don't update? By default from the offset address I scan 1370 x 4 bytes into an array and parse that. Maybe 1370 is too large. I'll have a gander at the memory tonight and see if that's the case.

**Comment by cjmanca** [comment]
I've seen this myself, and it's definitely not just because of old entries in RAM. If you close FFXIV and re-open it, all those old items disappear. If it were ram fragments, they would all still be there when you re-opened. It has to be something either in radar or in core APP that's not removing old entries when they disappear from the game.

**Comment by viion** [comment]
The core memory doesn't remove them, it isn't meant to and imo shouldn't, that's functionality that needs to be built into the application as a use case may want dead enemies, or enemies from a previous zone.

All the memory does is scan for a range of enemies or npcs, and they can still include old ones until FFXIV loops back around and replaces them.

**Comment by Icehunter** [comment]
So; it's my fault. When I converted the code over to a concurrent dictionary I failed to also put in code that when something is actually removed; go and remove it from the main dictionary to update the plugins.

I will be checking in some code to memory to handle this.

**Comment by Icehunter** [comment]
Going to test this out now:

https://github.com/Icehunter/ffxivapp-memory/commit/80d73cdc3b9e4ef3dff4780539ff958e575b1ea2

**Comment by cjmanca** [comment]
> The core memory doesn't remove them, it isn't meant to and imo shouldn't, that's functionality that needs to be built into the application as a use case may want dead enemies, or enemies from a previous zone.

FFXIVAPP keeps a list with all **current** entities. If your plugin wants to remember things after they die or disappear, you'd need to store that yourself in your plugin. It's not very reasonable to store every entity that APP ever sees forever, on the off chance that someone may want one of them someday. There would just be too many things stored for too long.

Keep in mind that when something dies, it is still a valid entity for a few seconds until it disappears (a valid entity with zero health), so that gives plenty of time to handle death vs disappearing for other reasons, if that's what you're concerned about.

**Comment by viion** [comment]
You can flush out old entries per scan, as your plugin will have obtained that data and it reduces the iteration count, but removing dead enemies should be part of a plugins choice, many enemies still load in memory even when dead which are valuable...

**Comment by cjmanca** [comment]
If it's in the game's memory, it's considered a current entity, regardless of whether it's dead or not.

In general, dead enemies disappear after a few seconds, and are then removed from game memory. Due to this current bug in APP, however, they weren't being removed from APP's collection, even though they were no longer in game memory.

**Comment by Icehunter** [comment]
Fixed in recent releases.
